// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageServer_SendMessage_FullMethodName = "/messageServer/sendMessage"
)

// MessageServerClient is the client API for MessageServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServerClient interface {
	SendMessage(ctx context.Context, in *Req, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Reply], error)
}

type messageServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServerClient(cc grpc.ClientConnInterface) MessageServerClient {
	return &messageServerClient{cc}
}

func (c *messageServerClient) SendMessage(ctx context.Context, in *Req, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Reply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MessageServer_ServiceDesc.Streams[0], MessageServer_SendMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Req, Reply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageServer_SendMessageClient = grpc.ServerStreamingClient[Reply]

// MessageServerServer is the server API for MessageServer service.
// All implementations must embed UnimplementedMessageServerServer
// for forward compatibility.
type MessageServerServer interface {
	SendMessage(*Req, grpc.ServerStreamingServer[Reply]) error
	mustEmbedUnimplementedMessageServerServer()
}

// UnimplementedMessageServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageServerServer struct{}

func (UnimplementedMessageServerServer) SendMessage(*Req, grpc.ServerStreamingServer[Reply]) error {
	return status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMessageServerServer) mustEmbedUnimplementedMessageServerServer() {}
func (UnimplementedMessageServerServer) testEmbeddedByValue()                       {}

// UnsafeMessageServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServerServer will
// result in compilation errors.
type UnsafeMessageServerServer interface {
	mustEmbedUnimplementedMessageServerServer()
}

func RegisterMessageServerServer(s grpc.ServiceRegistrar, srv MessageServerServer) {
	// If the following call pancis, it indicates UnimplementedMessageServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageServer_ServiceDesc, srv)
}

func _MessageServer_SendMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Req)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageServerServer).SendMessage(m, &grpc.GenericServerStream[Req, Reply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageServer_SendMessageServer = grpc.ServerStreamingServer[Reply]

// MessageServer_ServiceDesc is the grpc.ServiceDesc for MessageServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "messageServer",
	HandlerType: (*MessageServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "sendMessage",
			Handler:       _MessageServer_SendMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto.proto",
}
